<?php
/**
 * Created by PhpStorm.
 * User: lkk
 * Date: 17/11/13
 * Time: 下午5:19
 */

namespace Admin\Controller;

use Think\Controller;

class AdminChickenbatchTodayfeedDeliveryController extends AdminPublicController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        // 实例hua
        $this->_m = M($this->_table_name);
    }

    public function index()
    {
        // 分页
        $map = array();
        if(I('get.delivery_date')) $map['delivery_date'] = I('get.delivery_date');
        $page = (int)I('page');
        $data['page_limit']  = 20;
        $data['total_count'] = $this->_m->where($map)->count();
        $data['total_page']  = ceil($data['total_count']/$data['page_limit']);
        $data['now_page']    = ($page > 0 and $page <= $data['total_page']) ? $page : 1;
        $list = $this->_m->where($map)->page($page,$data['page_limit'])->order('delivery_date desc')->select();

        // 处理数据
        foreach ($list as $k=>$v)
        {
            $list[$k] = $this->disposeData($v);
        }

        $Page       = new \Think\Page($data['total_count'],$data['page_limit']);
        $show       = $Page->show();// 分页显示输出
        $this->assign('page',$show);// 赋值分页输出
        $this->assign('list',$list);
        $this->assign('count',$data['total_count']);
        $this->display();
    }

    public function add()
    {
        $data = I('post.');
        if($data) {

            // 其他价格
            $today_price = M('TodayPrice')->where('delivery_date="'.$data['delivery_date'].'"')->find();
            if(!$today_price) die($data['delivery_date'].'的价格还未填写!');
            if($this->_m->where('chicken_batch = '.$data['chicken_batch'].' and delivery_date="'.$data['delivery_date'].'"')->find()) die('该批次'.$data['delivery_date'].'已经结算!');
            $data['egg_price']  = $data['lay_eggs_weight']*$today_price['egg_price'];
            $data['feed_price'] = $data['feed_weight']*$today_price['feed_price'];

            // 结算日龄
            $chicken_batch = M('ChickenBatch')->where('id='.$data['chicken_batch'])->find();
            if(!$chicken_batch) die('结算批次不存在,结算失败');
            $data['age_in_days'] = $chicken_batch['age_in_days']+(strtotime($data['delivery_date'])-strtotime($chicken_batch['lairage_date']))/86400;

            if(!$this->_m->add($data)) die('添加失败');
            die('success');
        }
        $chicken_batch = M('ChickenBatch')->where('state=1')->select();
        $chicken_batch_info = M('ChickenBatch')->where('id='.I('get.chicken_batch'))->where('state=1')->find();
        if(!$chicken_batch) die('暂无需要结算的批次');

        $guess_age_in_days = $chicken_batch_info['age_in_days']+(strtotime(date('Y-m-d'))-strtotime($chicken_batch_info['lairage_date']))/86400;
        $this->assign('guess_age_in_days',$guess_age_in_days);
        $this->assign('chicken_batch',$chicken_batch);
        $this->assign('delivery_date',date('Y-m-d'));
        $this->display();
    }

    public function edit()
    {
        $id   = I('get.id') ? I('get.id') : I('post.id') ;
        $data = I('post.');

        $info = $this->_m->where('id='.$id)->find();
        if(!$info) die('未找到!');
        //if($info['state'] != 1) die('已经结算');

        if($data) {
            // 其他价格
            $today_price = M('TodayPrice')->where('delivery_date="'.$data['delivery_date'].'"')->find();
            if(!$today_price) die($data['delivery_date'].'的价格还未填写!');
            if($this->_m->where('id != '.$data['id'].' and chicken_batch = '.$data['chicken_batch'].' and delivery_date="'.$data['delivery_date'].'"')->find()) die('该批次'.$data['delivery_date'].'已经结算!');
            $data['egg_price']   = $data['lay_eggs_weight']*$today_price['egg_price'];
            $data['feed_price']  = $data['feed_weight']*$today_price['feed_price'];
            $data['age_in_days'] = $data['age_in_days'];

            // 结算日龄
            $chicken_batch = M('ChickenBatch')->where('id='.$data['chicken_batch'])->find();
            if(!$chicken_batch) die('结算批次不存在,结算失败');
            $data['age_in_days'] = $chicken_batch['age_in_days']+(strtotime($data['delivery_date'])-strtotime($chicken_batch['lairage_date']))/86400;
            if(!$this->_m->where('id='.$data['id'])->save($data)) die('修改失败');
            die('success');
        }


        $chicken_batch = M('ChickenBatch')->where('state=1')->select();
        if(!$chicken_batch) die('暂无需要结算的批次');
        $this->assign('chicken_batch',$chicken_batch);
        $this->assign('info',$info);
        $this->display();
    }

    public function confimDelivery()
    {
        $id = I('get.id');
        if($this->_m->where('id='.$id)->setField('state',2)) die('success');
        die('结算失败');
    }

    public function disposeData($arr)
    {
        $chicken_batch = M('ChickenBatch')->where('id='.$arr['chicken_batch'])->find();
        $arr['chicken_batch_name'] = $chicken_batch['name'];
        if(!$arr['age_in_days']) $arr['guess_age_in_days'] = $chicken_batch['age_in_days']+(strtotime($arr['delivery_date'])-strtotime($chicken_batch['lairage_date']))/86400;
        return $arr;
    }
}