<?php
namespace Admin\Controller;
/**
 * Created by PhpStorm.
 * User: wangbaojin
 * Date: 18/2/6
 * Time: 下午12:15
 */
class AdminAdvertisementController extends AdminPublicController
{
    private $_not_null = array(
        'title'       => '文字标题都不填,你是不是飘了',
        'article_url' => '文章链接都没有,你让我跳一跳?',
    );

    private $_pic_path = './Public/images/uploads/news';

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        // 实例hua
        $this->_m = M($this->_table_name);
    }

    public function index()
    {
        // 分页
        $map = array();
        if(I('get.title')) $map['title'] = array('like',"%".I('get.title')."%");
        $page = (int)I('page');
        $data['page_limit']  = 20;
        $data['total_count'] = $this->_m->where($map)->count();
        $data['total_page']  = ceil($data['total_count']/$data['page_limit']);
        $data['now_page']    = ($page > 0 and $page <= $data['total_page']) ? $page : 1;
        $list = $this->_m->where($map)->page($page,$data['page_limit'])->order('id desc')->select();

        // 处理数据
        foreach ($list as $k=>$v)
        {
            $list[$k] = $this->disposeData($v);
        }

        $Page = new \Think\Page($data['total_count'],$data['page_limit']);
        $show = $Page->show();// 分页显示输出
        $this->assign('page',$show);// 赋值分页输出
        $this->assign('list',$list);
        //echo "<pre>";
        //print_r($list);die;
        $this->assign('count',$data['total_count']);
        $this->display();
    }

    public function del()
    {
        $id  = I('get.id');
        $del = $this->_m->where('id='.$id)->delete();
        $msg = $del ? 'success' : '删除失败';
        die($msg);
    }

    public function add()
    {
        $data = I('post.');

        if($data) {

            $data['create_time'] = time();
            $data['newstime']    = strtotime($data['newstime']);
            $data['end_time']    = strtotime($data['end_time']);
            $res = $this->_m->add($data);
            if(!$res) die('添加失败');

            $msg = 'success';

            // 上传商品图片
            if($_FILES['pic']['name'])
            {
                $up_res = $this->uploadsImg($res);
                if($up_res['err_no']==1)
                {
                    foreach($up_res['info'] as $fk=>$file)
                    {
                        if($fk=='pic') $change_data['pic']  = $file['savepath'].$file['savename'];
                    }
                    $this->_m->where('id='.$res)->save($change_data);
                }
                else
                {
                    $msg .= $up_res['err_msg'];
                }
            }
            die($msg);
        }
        $this->display();
    }

    /*上传图片*/
    private function uploadsImg($savePath)
    {

        $data = array();
        if(!$_FILES)
        {
            $data['err_no']     = 2;
            $data['err_msg']    = '没有文件上传';
        }
        else
        {
            $rootPath = $this->_pic_path;
            directory($rootPath);
            //if(!is_dir($rootPath)) mkdir($rootPath);
            $upload = new \Think\Upload();// 实例化上传类
            $upload->maxSize   =     10240000;// 设置附件上传大小
            $upload->exts      =     array('jpg', 'gif', 'png', 'jpeg');// 设置附件上传类型
            $upload->rootPath  =     $rootPath; // 设置附件上传根目录
            $upload->autoSub   =     false;
            //$upload->savePath  =      '/'.$savePath.'/'; // 设置附件上传（子）目录
            $upload->savePath  =      '/'; // 设置附件上传（子）目录
            $upload->saveName  =      array('uniqid',$savePath.'_');

            // 上传文件
            $info   =   $upload->upload();
            if(!$info)
            {// 上传错误提示错误信息
                $data['err_no']     = 3;
                $data['err_msg']    = $upload->getError();
            }
            else
            {// 上传成功 获取上传文件信息
                $data['err_no']     = 1;
                $data['err_msg']    = 'success';
                $data['info']       = $info;
            }
        }
        return $data;
    }

    public function edit()
    {
        $id   = I('get.id');
        $data = I('post.');

        if(!$id) die('参数错误');

        if($data) {

            $data['newstime'] = strtotime($data['newstime']);
            $data['end_time'] = strtotime($data['end_time']);
            $res = $this->_m->where('id='.$id)->save($data);
            $msg = 'success';

            // 上传商品图片
            if($_FILES['pic']['name'])
            {
                $up_res = $this->uploadsImg($res);
                if($up_res['err_no']==1)
                {
                    foreach($up_res['info'] as $fk=>$file)
                    {
                        if($fk=='pic') $change_data['pic']  = $file['savepath'].$file['savename'];
                    }
                    $change_img_res = $this->_m->where('id='.$id)->save($change_data);
                }
                else
                {
                    $msg .= $up_res['err_msg'];
                }
            }
            if(!$res and !$change_img_res) die('修改失败');
            die($msg);
        }

        $info = $this->_m->where('id='.$id)->find();
        if(!$info) die('该记录不存在!');
        $info = $this->disposeData($info);
        $this->assign('info',$info);
        $this->display();
    }

    public function disposeData($arr)
    {
        /*创建时间*/
        $arr['create_date'] = date('Y-m-d',$arr['create_time']);

        /*发布时间*/
        $arr['newstime_date'] = date('Y-m-d H:i:s',$arr['newstime']);
        $arr['end_date']      = date('Y-m-d H:i:s',$arr['end_time']);

        /*图片*/
        if($arr['pic']) $arr['pic'] = getSelf().$this->_pic_path.$arr['pic'];

        return $arr;
    }
}