<?php
/**
 * Created by PhpStorm.
 * User: lkk
 * Date: 17/11/13
 * Time: 下午5:19
 */

namespace Admin\Controller;

use Think\Controller;

class AdminUserController extends AdminPublicController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        // 实例hua
        $this->_m = M($this->_table_name);
    }

    public function index()
    {
        // 分页
        $map = array();
        if(I('get.mobile')) $map['mobile'] = array('like',"%".I('get.mobile')."%");
        if(I('get.id'))     $map['id']     = I('get.id');
        if(I('get.full_name'))
        {
            $full_name = trim(I('get.full_name'));
            //if($full_name) $map['full_name'] = $full_name;
            // 微信昵称
            $idAry = M('UserWechatinfo')->where('wx_nick_name="'.base64_encode($full_name).'"')->getField('user_id',true);
            //echo M('UserWechatinfo')->getLastSql();die;
            if($idAry) $map['id'] = array('in',$idAry);
        }

        $page = (int)I('p');
        $data['page_limit']  = 20;
        $data['total_count'] = $this->_m->where($map)->count();
        $data['total_page']  = ceil($data['total_count']/$data['page_limit']);
        $data['now_page']    = ($page > 0 and $page <= $data['total_page']) ? $page : 1;
        $list = $this->_m->where($map)->page($page,$data['page_limit'])->order('id desc')->select();

        // 处理数据
        foreach ($list as $k=>$v)
        {
            $list[$k] = $this->disposeData($v);
        }

        $Page       = new \Think\Page($data['total_count'],$data['page_limit']);
        $show       = $Page->show();// 分页显示输出
        $this->assign('page',$show);// 赋值分页输出
        $this->assign('list',$list);
        $this->assign('count',$data['total_count']);
        $this->display();
    }

    public function changeMobile()
    {
        $id     = I('get.id');
        $mobile = I('get.mobile');

        if(!$id) die('参数错误');

        $info = $this->_m->where('id='.$id)->find();
        if(!$info) die('该记录不存在!');

        if($this->_m->where('id != '.$id.' and mobile='.$mobile)->find()) die('该手机号已被绑定!');

        if(!$this->_m->where('id='.$id)->setField('mobile',$mobile)) die('修改失败,请刷新重试');
        die('success');
    }

    public function edit()
    {
        $id   = I('get.id');
        $data = I('post.');
        if(!$id) die('参数错误');
        $info = $this->_m->where('id='.$id)->find();
        if(!$info) die('该记录不存在!');

        if($data)
        {
            if(!$this->_m->where('id='.$data['id'])->save($data)) die('添加失败');
            die('success');
        }

        $info = $this->disposeData($info);
        $this->assign('info',$info);
        $this->display();
    }

    public function changeSt()
    {
        $id   = I('get.id');
        if(!$id) die('参数错误');
        $info = $this->_m->where('id='.$id)->find();

        if(!$info) die('该记录不存在');

        $st = $info['user_st'] == 1 ? 2 : 1;
        if($this->_m->where('id='.$id)->setField('user_st',$st))
        {
            die('success');
        }
        die('修改失败!请刷新重试');
    }

    public function disposeData($arr)
    {
        $user_info = getUserInfoByUserId($arr['id']);
        if($user_info) $arr = $user_info['data'];

        // 鸡的数量
        $chick_num = M('Chicken')->where(' user_id= '.$arr['id'].' and (state=4 or state=5)')->count();
        $arr['buy_chicken_num'] = $chick_num ? $chick_num : 0;

        // 钱包
        $m = M('Wallet');

        $map['user_id']  = $arr['id'];
        $wallet_info     = $m->where($map)->find();

        if($wallet_info) $arr['wallet'] = $wallet_info;

        // 充值
        $pay_price = M('Recharge')->where('user_id='.$arr['id'])->SUM('pay_price');
        $arr['recharge'] = $pay_price ? $pay_price : 0;

        $withdrawals_map = array();
        $withdrawals_map['user_id']   = $arr['id'];
        // 支付宝账户
        $arr['zfb_list'] = M('Withdrawals')->where($withdrawals_map)->getField('zhifubao_account',true);
        $arr['zfb_list'] = array_unique($arr['zfb_list']);

        // 累计提现
        $withdrawals_map['pay_state'] = 4;
        $withdrawals_map['state']     = 2;
        $withdrawals = M('Withdrawals')->where($withdrawals_map)->SUM('pay_price');


        // 邀请好友
        $invite__map = array();
        $invite__map['invite_user_id'] = $arr['id'];
        $invite_buy = M('InviteBuy')->where($invite__map)->count();
        $arr['invite_buy'] = $invite_buy ? $invite_buy : 0;
        $invite__map['buy_state'] = 1;
        $invite_success_buy = M('InviteBuy')->where($invite__map)->count();
        $arr['invite_success_buy'] = $invite_success_buy ? $invite_success_buy : 0;

        $eggcoin_map = array();
        $eggcoin_map['user_id']     = $arr['id'];
        $eggcoin_map['state']       = 1;

        // 查看收益奖励发放token
        $eggcoin_map['reason_type'] = 1;
        $chick_eggcoin = M('EggcoinRecord')->where($eggcoin_map)->SUM('amount');
        $arr['chick_eggcoin'] = $chick_eggcoin ? $chick_eggcoin : 0;

        // 查看任务奖励发放token
        $eggcoin_map['reason_type'] = 3;
        $invite_eggcoin = M('EggcoinRecord')->where($eggcoin_map)->SUM('amount');
        $arr['invite_eggcoin'] = $invite_eggcoin ? $invite_eggcoin : 0;

        $arr['withdrawals'] =  $withdrawals ? $withdrawals : 0;

        return $arr;
    }
}